const { Command } = require('discord.js-commando');
const fetch = require('node-fetch');

module.exports = class Villager extends Command {
	constructor(client) {
		super(client, {
			name: 'acvillager',
			aliases: ['villager', 'ac_villager', 'acv'],
			group: 'animalcrossing',
			memberName: 'villager',
            description: 'Gets information on a specific villager',
            guildOnly: false,
            args: [
                {
                    key: 'villager',
                    prompt: 'Please enter a villager name.',
                    type: 'string',
                },
            ],
		});
    }
    
    async run(message, { villager }) {
        let index = villagerList.indexOf(villager.toLowerCase());
        if(index == -1) {
            message.reply(`Invalid villager name (${villager}). Please try again.`)
        } else {
            const url = `http://acnhapi.com/v1/villagers/${index + 1}`;
            fetch(url)
                .then(res => res.json())
                .then(person => {
                    let name = capitalize(villager)
                    let villagerEmbed = {
                        color: 0x696969,
                        title: name,
                        url: `https://animalcrossing.fandom.com/wiki/${name}`,
                        // description: `${person.species}, ${person.gender}`,
                        thumbnail: {
                            url: person.icon_uri,
                        },
                        fields: [
                            {
                                name: 'Catchprase',
                                value: `"${person["catch-phrase"]}"`,
                                inline: true
                            },
                            {
                                name: 'Species',
                                value: person.species,
                                inline: true
                            },
                            {
                                name: 'Gender',
                                value: person.gender,
                                inline: true
                            },
                            {
                                name: 'Personality',
                                value: person.personality,
                                inline: true
                            },
                            {
                                name: 'Birthday',
                                value: person["birthday-string"],
                                
                            },
                        ],
                        image: {
                            url: person.image_uri,
                        },
                        timestamp: new Date(),
                        footer: {
                            text: 'Cheeberbot',
                            //icon_url: 'https://i.imgur.com/wSTFkRM.png',
                        },
                    };
                    message.reply({embed: villagerEmbed});
                })
                .catch(err => {message.reply(`Failed to retrieve villager information for ${villager}.`);})
        }
    };
};

let capitalize = str => {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

villagerList = ["cyrano", 
"antonio", 
"pango", 
"anabelle", 
"snooty", 
"annalisa", 
"olaf", 
"teddy", 
"pinky", 
"curt", 
"chow", 
"nate", 
"groucho", 
"tutu", 
"ursala", 
"grizzly", 
"paula", 
"ike", 
"charlise", 
"beardo", 
"klaus", 
"megan", 
"jay", 
"robin", 
"anchovy", 
"twiggy", 
"jitters", 
"piper", 
"admiral", 
"midge", 
"jacob", 
"lucha", 
"jacques", 
"peck", 
"sparro", 
"angus", 
"rodeo", 
"stu", 
"t-bone", 
"coach", 
"vic", 
"bob", 
"mitzi", 
"rosie", 
"olivia", 
"kiki", 
"tangy", 
"punchy", 
"purrl", 
"moe", 
"kabuki", 
"kid cat", 
"monique", 
"tabby", 
"stinky", 
"kitty", 
"tom", 
"merry", 
"felicity", 
"lolly", 
"ankha", 
"rudy", 
"katt", 
"raymond", 
"bluebear", 
"maple", 
"poncho", 
"pudge", 
"kody", 
"stitches", 
"vladimir", 
"murphy", 
"olive", 
"cheri", 
"june", 
"pekoe", 
"chester", 
"barold", 
"tammy", 
"judy", 
"goose", 
"benedict", 
"egbert", 
"ava", 
"becky", 
"plucky", 
"knox", 
"broffina", 
"ken", 
"patty", 
"tipper", 
"norma", 
"naomi", 
"alfonso", 
"alli", 
"boots", 
"del", 
"sly", 
"gayle", 
"drago", 
"fauna", 
"bam", 
"zell", 
"bruce", 
"deirdre", 
"lopez", 
"fuchsia", 
"beau", 
"diana", 
"erik", 
"goldie", 
"butch", 
"lucky", 
"biskit", 
"bones", 
"portia", 
"walker", 
"daisy", 
"cookie", 
"maddie", 
"bea", 
"mac", 
"marcel", 
"benjamin", 
"cherry", 
"shep", 
"bill", 
"joey", 
"pate", 
"maelle", 
"deena", 
"pompom", 
"mallary", 
"freckles", 
"derwin", 
"drake", 
"scoot", 
"weber", 
"miranda", 
"ketchup", 
"gloria", 
"molly", 
"quillson", 
"opal", 
"dizzy", 
"big top", 
"eloise", 
"margie", 
"paolo", 
"axel", 
"ellie", 
"tucker", 
"tia", 
"cyd", 
"lily", 
"ribbot", 
"frobert", 
"camofrog", 
"drift", 
"wart jr.", 
"puddles", 
"jeremiah", 
"tad", 
"cousteau", 
"huck", 
"prince", 
"jambette", 
"raddle", 
"gigi", 
"croque", 
"diva", 
"henry", 
"chevre", 
"nan", 
"billy", 
"gruff", 
"velma", 
"kidd", 
"pashmina", 
"sherb", 
"cesar", 
"peewee", 
"boone", 
"louie", 
"boyd", 
"violet", 
"al", 
"rocket", 
"hans", 
"hamlet", 
"apple", 
"graham", 
"rodney", 
"soleil", 
"clay", 
"flurry", 
"hamphrey", 
"rocco", 
"bubbles", 
"bertha", 
"biff", 
"bitty", 
"harry", 
"hippeux", 
"buck", 
"victoria", 
"savannah", 
"elmer", 
"roscoe", 
"winnie", 
"ed", 
"cleo", 
"peaches", 
"annalise", 
"clyde", 
"colton", 
"papi", 
"julian", 
"reneigh", 
"yuka", 
"alice", 
"melba", 
"sydney", 
"gonzo", 
"ozzie", 
"canberra", 
"lyman", 
"eugene", 
"kitt", 
"mathilda", 
"carrie", 
"astrid", 
"sylvia", 
"walt", 
"rooney", 
"marcie", 
"bud", 
"elvis", 
"rex", 
"leopold", 
"mott", 
"rory", 
"lionel", 
"nana", 
"simon", 
"tammi", 
"monty", 
"elise", 
"flip", 
"shari", 
"deli", 
"dora", 
"limberg", 
"bella", 
"bree", 
"samson", 
"rod", 
"candi", 
"rizzo", 
"anicotti", 
"broccolo", 
"moose", 
"bettina", 
"greta", 
"penelope", 
"chadder", 
"octavian", 
"marina", 
"zucker", 
"queenie", 
"gladys", 
"sandy", 
"sprocket", 
"julia", 
"cranston", 
"phil", 
"blanche", 
"flora", 
"phoebe", 
"apollo", 
"amelia", 
"pierce", 
"buzz", 
"avery", 
"frank", 
"sterling", 
"keaton", 
"celia", 
"aurora", 
"roald", 
"cube", 
"hopper", 
"friga", 
"gwen", 
"puck", 
"wade", 
"boomer", 
"iggly", 
"tex", 
"flo", 
"sprinkle", 
"curly", 
"truffles", 
"rasher", 
"hugh", 
"lucy", 
"spork", 
"cobb", 
"boris", 
"maggie", 
"peggy", 
"gala", 
"chops", 
"kevin", 
"pancetti", 
"agnes", 
"bunnie", 
"dotty", 
"coco", 
"snake", 
"gaston", 
"gabi", 
"pippy", 
"tiffany", 
"genji", 
"ruby", 
"doc", 
"claude", 
"francine", 
"chrissy", 
"hopkins", 
"o'hare", 
"carmen", 
"bonbon", 
"cole", 
"mira", 
"tank", 
"rhonda", 
"spike", 
"hornsby", 
"merengue", 
"renée", 
"vesta", 
"baabara", 
"eunice", 
"stella", 
"cashmere", 
"willow", 
"curlos", 
"wendy", 
"timbra", 
"frita", 
"muffy", 
"pietro", 
"dom", 
"peanut", 
"blaire", 
"filbert", 
"pecan", 
"nibbles", 
"agent s", 
"caroline", 
"sally", 
"static", 
"mint", 
"ricky", 
"cally", 
"tasha", 
"sylvana", 
"poppy", 
"sheldon", 
"marshal", 
"hazel", 
"rolf", 
"rowan", 
"tybalt", 
"bangle", 
"leonardo", 
"claudia", 
"bianca", 
"chief", 
"lobo", 
"wolfgang", 
"whitney", 
"dobie", 
"freya", 
"fang", 
"vivian", 
"skye", 
"kyle", 
"audie"]